### ISSUE TITLE
4.6.18

### ISSUE THREAD

**Issue by jraeglasgow** [jraeglasgow/Isis-1-1#3]
## **Last Week Activities** 
- Calls:
- Total Emails:
- New Cadences Launched: 
- Meetings Set:
- Most Effective Personas:
- Stack Ranking/Focus from ESR: 

## **Goals**
- This Week Activity
    - Calls:
    - Total Emails:
    - New Cadences Launched 
- Personal: What are your daily habits that will make you better?   
- BHAG: Work/Personal 

## **Events**
Upcoming Opportunity 
- Constellation DC: April 19

## Feedback and Questions 
-

**Comment by isisdill** [comment]
Last Week's Activities:

- I got some much needed pitch practice with Kamilah.
- I sent 400 emails to top targets to invite them to Constellation.
- I got 2 teams to register for Constellation -Dept. of homeland security and FBI. (so far)
- I sent over 50 Linkedin messages to invite more people to the event.
- I synced with more people from my direct team (SE Jamie, AE Dave, and RD Elizabeth)
- I set my FIRST qualified meeting via inbound sales line (The D.E. Shaw Group)
- I created messaging for 2 Yesware sequences this week - Roadmap for Govt. and FedRamp

**Comment by jraeglasgow** [comment]
**Action Items for @isisdill** 

- [ ] Create follow up sequence (or steal) from event for attendees and non-attendees 
- [ ] Connect with Kamilah on who has gotten roadmap messaging and prepare your's and who you are going to send it to
- [ ] Pre-pare for working sessions with Jess- outline in detail 
- What you know
- What you feel you are missing
-Present where Kamilah left off, what the plan was for May , etc. 

**Action Items for Jess** 
- [ ] Schedule working session, review areas for Isis to cover

**Comment by isisdill** [comment]
Personal growth:

I really want to understand the secondary questions that will extract the most pain from the prospect in order to set quality meetings that tie to ARR for the east team.

How I define pain for the prospect is something that impacts them in terms of time, cost, risk, and revenue if not solved within a certain time frame.

**Comment by jraeglasgow** [comment]
@isisdill Friendly reminder get everything on your checklist above ready for our working session 👍
