### ISSUE TITLE
4.13.18

### ISSUE THREAD

**Issue by jraeglasgow** [jraeglasgow/Isis-1-1#4]
## **Last Week Activities** 
- Calls: 83
- Total Emails: 83
- New Cadences Launched: Created two post attendance sequences for D.C. Constellation
- Meetings Set: none but I confirmed six people for constellation via cold call.
- Most Effective Personas: Executive (VP/SVP/CIO/CTO) more familiar with C-suite the other personas in government are more vague.
- Stack Ranking/Focus from ESR: Getting on the same page about my new top 5 target accounts and setting up time to discuss context around accounts because Dave has engaged with them in the past.

## **Goals**
- This Week Activity
    - Calls: 20
    - Total Emails: 20
    - New Cadences Launched: Launch post attendance sequences on Sunday 3/15 @ 5pm EST.
- Personal: What are your daily habits that will make you better? Transition my calendar from full training to a ramped EBR. 
- BHAG: Work/Personal: Launch my sequences on Sunnday 3/15 @ 5pm EST and set up follow up meeting to achieve ramp quota. Personal Goal: See the white house in D.C. 🇺🇸 🆒 

## **Events**
Upcoming Opportunity 
- Constellation DC: April 19

## Feedback and Questions 
-

**Comment by isisdill** [comment]
# Working Session on April 11th

**What you know:**
1. FedRamp and Why it's important to GitHub
1. Why they buy = Security & Policy
1. Government is seasonally driven and the fiscal year ends of Sept. 30th. 
1. 70-80% of govt. spending happens in Aug & Sept
1. Lots of reference selling (similar agencies with GitHub instances) 
1. We lose to status quo. (FUD) 


 **What you feel you are missing:**
1. Missing an in-depth review of my target accounts. Dave will help with during our sync but it's going to be critical to leverage past conversations and meetings to push opps forward. 
1. Experience with inbound resellers/govt. request
1.  Where does Government collab on different target accounts? I.e. salesforce, Halp, google docs. etc



-Present where Kamilah left off, what the plan was for May , etc.

**Comment by jraeglasgow** [comment]
What we are missing:

1) 
To Do for @isisdill :
- [ ] where is Dave working out of? 
- [ ] 5 Top targets to create master issue on
- [ ] Add Jess to all call you are on and set goal to be on four per week

**Comment by isisdill** [comment]
Reseller Inquiries
1. Are you an official GitHub Partner? Check here: GH Partners w/ Signed Agreements
2. Who is the end client? I’d like to learn more about the end user’s use case. Can you provide their contact information.

**Pitch**
Isis here with GitHub. Just wanted to touch base with you to learn a little bit more about your use case and understand why you guys are looking at GitHub. 


Just wanted to talk about the pricing with you. 
Seats are sold in packs of 10 with a minimum purchase of 10 seats. List price is $250 per seat per year

After they talk about their use case….. you ask: how mission critical is the code? Would there be some issues if this got out? Would you still have a job tomorrow?

(The code is critical…blah blah) then you recommend the business hosted or on prem.

**Comment by isisdill** [comment]
# Top Target Accounts for May
_Use case: From GitHub Business to GitHub Enterprise_
- [ ] Nasa
- [ ] USGS
- [ ] NIH
- [ ] NIST
- [ ] Lawrence Berkeley Lab
