### ISSUE TITLE
May Planning - 4.27.18 1/1

### ISSUE THREAD

**Issue by jraeglasgow** [jraeglasgow/Isis-1-1#5]
Hi @isisdill , 

For our last one-on-one this month, I want to focus on a plan for May as it relates to your goals and plan of attack so far. Below is an outline of our monthly approach to success.

Please let me know if you have any questions and I look forward to reviewing this together on Friday. Note, the outline is all that needs to be done by the meeting, I wanted to give you a full week to finish your assets so you can focus on the end of the month as well! 
-Jess
___________________________________________________________________________________________________________
**May Plan** 

**What**: Need 7 Meetings to Hit - 11 to Hit 150%
**Who**: Top 5 Accounts that will get you to 150% - This is our goal for you, what is your goal for yourself and when/how are you going to get there?
**When**: 
- Week 1 Activities 
- Week 2 Activities 
- Week 3 Activities
- Week 4 Activities 

**How**:
- Workflow: tools used, execution details: from working session to further look at flushing out activities 
- cadences used -

**Action Items**: 
- [ ] **Who**: Pick Top 5 Accounts and Finish Master Issue and Tier Sheet for Each by EOD Monday, April 30th 
- [ ] **When**: Map which activities to weeks to create plan to reach goal of 11 meetings 
- [ ] **How**: outline ( high level example of how you are going to execute your plan for May) 

**April Feedback** 
- You have done a fantastic job of proactively connecting the dots and looking for where you need to organize in the near future to ensure your success. Leverage this strength for your first full month on quota and let's see what you can do when you are fully ramped! 
- Be aware and proactive of the dates you will be expecting yourself to bring in meetings. Then, work backwards. How are you going to get there?
- Good job asking for feedback and keeping yourself organized with content. 

**Assets**: 

- [SalesDev Account Tier/Mapping Template
](https://docs.google.com/spreadsheets/d/1W2FbnQrdPdLaCUsVQPJQq7YcUmN4IgAlRPA2xkqnlI4/edit#gid=1762991169)
- Master Issue Template 
## Company X

**SFDC** (link to Salesforce search for 'Company X')
**LinkedIn** 
**DiscoverOrg**
**Master spreadsheet**
**HQ:**  

#### VCS info
- **Current VCS:** 
- **Past GitHub trials:** 
- **Noticeable GitHub.com presence?** 

#### Context
- **Any similar customers?** (look for trends, key words, what's driving change?)
- **Any known tech initiatives?** (could be based on past conversations and/or on current info in the news)
- **Any known BUs? Which ones are we approaching?**
- **Key stakeholders:** (could be based on past conversations and/or on current info in the news)

#### 1st campaign: [who's being targetted]  
- **Why them?**
- **Target contacts:** (individuals, personas, or a specific BU)
  - ...

### Links to related Issues, Halp threads, SFDC notes
- ...

**Comment by isisdill** [comment]
**May Plan** 

**What**: Need 7 Meetings to Hit - 11 to Hit 150%
**Who**: Top 5 Accounts that will get you to 150% 
**BHAG**: SDR of the Year. 🏆 

**When**: 
Week 1 Activities:
 - Launch 100 prospects into RoadMap Sequence.
- Finish Constellation follow-up.
- make 50 dials/day.

Week 2 Activities:
- 
- Week 3 Activities
- Week 4 Activities 

**How**:
- Workflow: tools used, execution details: from working session to further look at flushing out activities 
- cadences used -

**Action Items**: 
- [ ] **Who**: Pick Top 5 Accounts and Finish Master Issue and Tier Sheet for Each by EOD Monday, April 30th 
- [ ] **When**: Map which activities to weeks to create plan to reach goal of 11 meetings 
- [ ] **How**: outline ( high level example of how you are going to execute your plan for May)

**Comment by isisdill** [comment]
# **Agenda for 1:1**

- Check in -
- Roadblocks and wins for the week.
- Goals for the rest of May
- AWS Public Summit ( June 20-22)- When do I book hotel & flight?

## Goals for the rest of May

-Follow up with leads who attended the AWS DevOps/SAO Event (Fink shared leads last Thursday)
- Discuss workflow. Yesware and I are not in sync at the moment. 
- Figure out how to create lead views for better workflow
